[tools]
rojo = "rojo-rbx/rojo@7.4.0-rc3"
wally = "UpliftGames/wally@0.3.2"
stylua = "johnnymorganz/stylua@0.19.1"
selene = "Kampfkarren/selene@0.26.1"
luau-lsp = "johnnymorganz/luau-lsp@1.26.0"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
